repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master, --pattern, '\d\.\d\.\d']
      - id: trailing-whitespace

  - repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
      - id: markdownlint

  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tflint

  - repo: local
    hooks:
      - id: circleci-validate
        name: circleci validate
        entry: circleci config validate
        language: system
        files: .circleci/config.yml
